-- Events with Nick production database schema
-- Run this in Supabase SQL Editor when you are ready for real multi-device bookings.
-- Column names are quoted to match the website JavaScript fields.
-- The policies below are suitable for presentation/testing. For final production,
-- replace broad anon policies with Supabase Auth owner-only policies.

create table if not exists public.bookings (
  id text primary key,
  "dateCreated" timestamptz default now(),
  name text not null,
  phone text not null,
  email text,
  "preferredCommunication" text,
  "altContact" text,
  "eventType" text,
  "eventDate" date,
  guests text,
  location text,
  package text,
  budget text,
  message text,
  status text default 'New',
  priority text default 'Normal',
  notes text,
  "quoteAmount" numeric,
  "assignedTo" text default 'Nick'
);

-- Safe upgrade columns if you already ran an older Events with Nick schema.
alter table public.bookings add column if not exists "preferredCommunication" text;
alter table public.bookings add column if not exists "altContact" text;

create table if not exists public.site_settings (
  id text primary key default 'main',
  settings jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.quote_pricing (
  id text primary key default 'main',
  pricing jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.banking_details (
  id text primary key default 'main',
  banking jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  image text not null,
  created_at timestamptz default now()
);

alter table public.bookings enable row level security;
alter table public.site_settings enable row level security;
alter table public.quote_pricing enable row level security;
alter table public.banking_details enable row level security;
alter table public.gallery_items enable row level security;

-- Re-run safe: remove old presentation policies before creating them again.
drop policy if exists "Public can create bookings" on public.bookings;
drop policy if exists "Owner can read bookings" on public.bookings;
drop policy if exists "Owner can update bookings" on public.bookings;
drop policy if exists "Owner can delete bookings" on public.bookings;
drop policy if exists "Public can read site settings" on public.site_settings;
drop policy if exists "Presentation can insert site settings" on public.site_settings;
drop policy if exists "Presentation can update site settings" on public.site_settings;
drop policy if exists "Presentation can read pricing" on public.quote_pricing;
drop policy if exists "Presentation can insert pricing" on public.quote_pricing;
drop policy if exists "Presentation can update pricing" on public.quote_pricing;
drop policy if exists "Presentation can read banking" on public.banking_details;
drop policy if exists "Presentation can insert banking" on public.banking_details;
drop policy if exists "Presentation can update banking" on public.banking_details;
drop policy if exists "Public can read gallery" on public.gallery_items;
drop policy if exists "Presentation can insert gallery" on public.gallery_items;
drop policy if exists "Presentation can delete gallery" on public.gallery_items;

-- Public users may insert booking enquiries from the public website.
create policy "Public can create bookings" on public.bookings
for insert with check (true);

-- Presentation/testing policies for the owner portal.
create policy "Owner can read bookings" on public.bookings for select using (true);
create policy "Owner can update bookings" on public.bookings for update using (true);
create policy "Owner can delete bookings" on public.bookings for delete using (true);

-- Site settings can be read by the public website and edited by the presentation owner portal.
create policy "Public can read site settings" on public.site_settings for select using (true);
create policy "Presentation can insert site settings" on public.site_settings for insert with check (true);
create policy "Presentation can update site settings" on public.site_settings for update using (true);

-- Pricing and banking are used by the owner portal for quotes.
create policy "Presentation can read pricing" on public.quote_pricing for select using (true);
create policy "Presentation can insert pricing" on public.quote_pricing for insert with check (true);
create policy "Presentation can update pricing" on public.quote_pricing for update using (true);

create policy "Presentation can read banking" on public.banking_details for select using (true);
create policy "Presentation can insert banking" on public.banking_details for insert with check (true);
create policy "Presentation can update banking" on public.banking_details for update using (true);

-- Gallery images can be read by the website and managed from the presentation owner portal.
create policy "Public can read gallery" on public.gallery_items for select using (true);
create policy "Presentation can insert gallery" on public.gallery_items for insert with check (true);
create policy "Presentation can delete gallery" on public.gallery_items for delete using (true);
